import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Frontend Mentor | Tic Tac Toe",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  //extra homework: add a home button that goes back to home "/" using the app icon
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-dvh flex-col items-center justify-center border-solid border-lime-500 bg-main-bg text-text">
        <Link href="/">Home</Link>
        {children}
      </body>
    </html>
  );
}
